version: '3'

services:

  mysql:
    image: mysql:latest
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: "no"
    networks:
      - stats

  sessions:
    build: ./
    env_file: .env
    depends_on:
      - mysql
    command: "python -m main"
    volumes:
      - ./:/app
    networks:
      - stats

networks:
  stats:

volumes:
  mysql-data: